import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const input = path.join(root, "src", "app", "globals.css");
const outCss = path.join(root, ".tmp.tailwind.css");
const outTs = path.join(root, "src", "app", "compiledCss.ts");

execFileSync(
  process.platform === "win32" ? "npx.cmd" : "npx",
  ["tailwindcss", "-i", input, "-o", outCss, "--minify"],
  { cwd: root, stdio: "inherit" },
);

const css = readFileSync(outCss, "utf8");
const contents = `// Generated by scripts/build-css.mjs\nexport const compiledCss = ${JSON.stringify(css)} as const;\n`;
writeFileSync(outTs, contents);

